# Spring configurations
spring:
  profiles:
    active: "´prod"
  main:
    allow-bean-definition-overriding: false
  # Database
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Token configuration
jwt:
  secret: bezKoderSecretKey
  expiration: 3600000
